version: "3"
services: 
  web:
    image: openjdk
    volumes:
      - "$PWD/target:/var/opt"
    ports:
      - "9002:9000"
    command: java -jar /var/opt/springbookdemo01-0.0.1-SNAPSHOT.jar
  db:
    image: mysql
    volumes:
      - "$PWD/dbdata:/var/lib/mysql"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
       - MYSQL_ROOT_PASSWORD=123
